/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function AsusRog(props) {
  const { nodes, materials } = useGLTF("/3dmodels/ASUS Rog.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.07, 0]} scale={[1.69, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Matte Black"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hdmi.geometry}
          material={materials.Keycaps}
          position={[-0.95, 0.03, -0.39]}
          scale={[0.08, 0.02, 0.07]}
        >
          <group position={[0.01, 0.3, -0.02]} scale={[0.04, 0.22, 0.71]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube004.geometry}
              material={materials.Gold}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube004_1.geometry}
              material={materials.Keycaps}
            />
          </group>
        </mesh>
        <group
          position={[0.95, 0.03, -0.07]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[-0.02, -0.03, -0.02]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials.Keycaps}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={materials.Gold}
          />
        </group>
        <group
          position={[0.72, 0.04, 0.13]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.04, 0.03, 0.06]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={materials.Keycaps}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012_1.geometry}
            material={materials.Glow}
          />
        </group>
        <group
          position={[-0.95, 0.03, -0.76]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.01, 0.03, 0.01]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials.Keycaps}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.Body}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen.geometry}
          material={materials["Matte Black"]}
          position={[0, 0.08, -0.94]}
          rotation={[-1.63, 0, 0]}
        >
          <group
            position={[0, 0.04, -0.02]}
            rotation={[1.57, 0, 0]}
            scale={[0.99, 1, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane006.geometry}
              material={materials.Keycaps}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane006_1.geometry}
              material={materials.Body}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Acer-Logo_2011001"].geometry}
            material={materials["Acer-Logo_2011"]}
            position={[0, 0.11, 0.93]}
            rotation={[-3.14, 0, Math.PI]}
            scale={[0.15, 0.26, 0.51]}
          />
          <group position={[0, 0.07, 1.05]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane004.geometry}
              material={materials.Keycaps}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane004_1.geometry}
              material={materials.Display}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Acer-Logo_2011"].geometry}
              material={materials["Acer-Logo_2011"]}
              position={[0, 0, -0.9]}
              rotation={[-3.14, 0, 0]}
              scale={[0.07, 0.12, 0.19]}
            />
            <group
              position={[0, 0, 0.8]}
              rotation={[3.14, 0, 0]}
              scale={[-0.02, 0, -0.03]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004.geometry}
                material={materials.Keycaps}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004_1.geometry}
                material={materials["Web cam"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004_2.geometry}
                material={materials["Webcam lens"]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Full_HD_Sticker.geometry}
              material={materials["Full HD Sticker"]}
              position={[-0.69, -0.01, -0.9]}
              rotation={[-3.14, 0, 0]}
              scale={[0.07, 0.11, 0.11]}
            />
          </group>
        </mesh>
        <group position={[-0.94, 0.03, -0.59]} scale={[0.59, 0.2, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={materials.Body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.Keycaps}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials.Gold}
          />
        </group>
        <group
          position={[0.94, 0.03, -0.66]}
          rotation={[0, 0, Math.PI]}
          scale={[0.59, 0.2, 1]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials.Body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_1.geometry}
            material={materials.Keycaps}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_2.geometry}
            material={materials.Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_3.geometry}
            material={materials.Blue}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.USB_Metal.geometry}
          material={materials.Keycaps}
          position={[-0.94, 0.03, -0.17]}
          scale={[0.03, 0.02, 0.07]}
        >
          <group position={[0.23, 0.2, 0.01]} scale={[-1.05, -0.29, -0.81]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube012.geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube012_1.geometry}
              material={materials.Gold}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.USB_Metal_2.geometry}
          material={materials.Keycaps}
          position={[0.94, 0.03, -0.22]}
          rotation={[0, 0, Math.PI]}
          scale={[0.03, 0.02, 0.07]}
        >
          <group
            position={[0.23, -0.23, 0.01]}
            rotation={[Math.PI, 0, 0]}
            scale={[-1.05, -0.29, -0.81]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube014.geometry}
              material={materials.Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube014_1.geometry}
              material={materials.Gold}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ryzen_Sticker.geometry}
          material={materials["Ryzen Sticker"]}
          position={[-0.86, 0.06, 0.86]}
          scale={[0.08, 0.13, 0.13]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RTX_Sticker.geometry}
          material={materials["RTX Sticker"]}
          position={[-0.68, 0.06, 0.86]}
          scale={[0.07, 0.13, 0.13]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps_lable_3.geometry}
        material={materials["Keycaps lable 3"]}
        position={[0, 0.13, -0.31]}
        scale={0.91}
      />
    </group>
  );
}

useGLTF.preload("/3dmodels/ASUS Rog.glb");
