/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function JBLHeadphones(props) {
  const { nodes, materials } = useGLTF("/3dmodels/JBLHeadphone.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001.geometry}
        material={materials["Материал.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus003.geometry}
        material={materials["Материал.001"]}
        position={[0, -0.04, -0.01]}
        rotation={[-0.45, 0, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Окружность.geometry}
        material={materials["Материал.001"]}
        position={[0, -0.08, -0.04]}
        rotation={[1.12, 0, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Окружность001.geometry}
        material={materials["Материал.001"]}
        position={[0, -0.08, -0.04]}
        rotation={[1.12, 0, 0]}
        scale={-0.01}
      />
      <group
        position={[0, -0.09, -0.06]}
        rotation={[-0.45, 0, 0]}
        scale={[0.01, 0.01, 0.02]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Куб_1.geometry}
          material={materials["Материал.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Куб_2.geometry}
          material={materials["Материал.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб001.geometry}
        material={materials["Материал.001"]}
        position={[0, -0.09, -0.06]}
        rotation={[-0.45, 0, 0]}
        scale={[0.01, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus002.geometry}
        material={materials["Материал.003"]}
      />
    </group>
  );
}

useGLTF.preload("/3dmodels/JBLHeadphone.glb");
