/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Macbookpro(props) {
  const { nodes, materials } = useGLTF("/3dmodels/macbookpro.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.03, -0.28]} rotation={[-0.26, 0, 0]} scale={0.26}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003.geometry}
          material={materials["Material.008"]}
          position={[0.01, 0.06, 0.01]}
          rotation={[1.81, 0, 0]}
          scale={[0.04, 0.04, 0.05]}
        />
        <group
          position={[0, -0.05, -0.02]}
          rotation={[1.59, 0, 0]}
          scale={1.06}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials["body.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials["black.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_2.geometry}
            material={materials["screen.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_3.geometry}
            material={materials["dark.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_4.geometry}
            material={materials["glass.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_5.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_6.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_7.geometry}
            material={materials["glass.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_8.geometry}
            material={materials["Apple-logo.001"]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["black.005"]}
        position={[-0.39, 0.02, -0.19]}
        scale={[0.01, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials.key}
        position={[0.14, 0.03, -0.17]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["body.001"]}
        position={[-0.4, 0.03, -0.21]}
        scale={0}
      />
      <group position={[0.32, 0.03, -0.21]} scale={0}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials["body.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_2.geometry}
          material={materials["black.006"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials["body.001"]}
        position={[0, 0.02, 0.15]}
        scale={0.12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials["black.005"]}
        position={[-0.39, 0.02, -0.19]}
        scale={[0.01, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials["black.007"]}
        position={[-0.39, 0.02, -0.18]}
        scale={[0.01, 0, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials["black.005"]}
        position={[-0.39, 0.02, -0.23]}
        scale={[0.01, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials["black.005"]}
        position={[-0.39, 0.02, -0.23]}
        scale={[0.01, 0, 0]}
      />
      <group position={[0, 0.02, 0]} rotation={[-0.02, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials["body.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_2.geometry}
          material={materials["Dark.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_3.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials["black.007"]}
        position={[-0.39, 0.02, -0.22]}
        scale={[0.01, 0, 0.01]}
      />
      <group position={[0.01, 0.03, -0.09]} scale={0.26}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials.key}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_2.geometry}
          material={materials["key.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_3.geometry}
          material={materials["Material.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3dmodels/macbookpro.glb");