/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MISmarTV(props) {
  const { nodes, materials } = useGLTF("/3dmodels/MI SMART TV.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0.73, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.6]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={nodes.Plane_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_4.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.008"]}
        position={[0.34, 0.73, -0.49]}
        rotation={[0, 0, -1.6]}
        scale={0.15}
      />
      <group
        position={[0.34, 0.81, -0.45]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[-0.01, -0.02, -0.01]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials["YELLOW RUB"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_3.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_4.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_5.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_6.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_7.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.006"]}
        position={[0.33, 0.53, -0.45]}
        scale={[-0.01, -0.02, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0.33, 0.45, -0.45]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.32, 0.46, -0.45]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.33, 0.45, -0.45]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.STAND}
        position={[0, 0.06, -0.37]}
        scale={[0.07, 0.02, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.011"]}
        position={[-0.02, 0.15, -0.3]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.GLASS}
        position={[0, 0.83, -0.22]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.48}
      />
    </group>
  );
}

useGLTF.preload("/3dmodels/MI SMART TV.glb");
