import "./globals.css";
import { Inter } from "next/font/google";

import Nav from "./Components/Nav";
import Providers from "./Components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Nav></Nav>
          {children}  
          {/* <h2>Footer</h2> */}
        </Providers>
      </body>
    </html>
  );
}
